title: Docker Docs
baseURL: https://docs.docker.com
refLinksErrorLevel: WARNING
enableGitInfo: true
dataDir: _data
disablePathToLower: true

markup:
  tableOfContents:
    startLevel: 2
    endLevel: 3
  goldmark:
    extensions:
      typographer: false
    parser:
      wrapStandAloneImageWithinParagraph: false
      attribute:
        block: true
    renderer:
      unsafe: true
  highlight:
    noClasses: false

related:
  includeNewer: true
  indices:
    # - name: topics
    # weight: 100
    - name: keywords
      weight: 40
  threshold: 80
  toLower: false

module:
  hugoVersion:
    extended: true
    min: "0.109.0"
  imports:
    - path: github.com/moby/moby
      ignoreImports: true
      mounts:
        - source: docs/api
          target: content/engine/api
          includeFiles: "**.md"
        - source: docs/api
          target: static/reference/engine
          includeFiles: "*.yaml"
    - path: github.com/moby/buildkit
      ignoreImports: true
      mounts:
        - source: frontend/dockerfile/docs/reference.md
          target: content/engine/reference/builder.md
        - source: docs/buildkitd.toml.md
          target: content/build/buildkit/toml-configuration.md
        - source: docs/attestations/slsa-definitions.md
          target: content/build/attestations/slsa-definitions.md
        - source: docs/attestations/attestation-storage.md
          target: content/build/attestations/attestation-storage.md
    - path: github.com/docker/cli
      mounts:
        - source: docs/extend
          target: content/engine/extend
          excludeFiles:
          - "**/index.md"
        - source: docs/extend/index.md
          target: content/engine/extend/_index.md
        - source: docs/deprecated.md
          target: content/engine/deprecated.md
        - source: docs/reference/run.md
          target: content/engine/reference/run.md
        - source: docs/reference/commandline/cli.md
          target: content/engine/reference/commandline/cli.md
        - source: docs/reference/commandline/dockerd.md
          target: content/engine/reference/commandline/dockerd.md
    - path: github.com/docker/compose-cli
      ignoreImports: true
      mounts:
        - source: docs/aci-compose-features.md
          target: content/cloud/aci-compose-features.md
        - source: docs/aci-container-features.md
          target: content/cloud/aci-container-features.md
        - source: docs/ecs-architecture.md
          target: content/cloud/ecs-architecture.md
        - source: docs/ecs-compose-examples.md
          target: content/cloud/ecs-compose-examples.md
        - source: docs/ecs-compose-features.md
          target: content/cloud/ecs-compose-features.md
    - path: github.com/distribution/distribution
      ignoreImports: true
      mounts:
      - source: docs
        target: content/registry
        excludeFiles:
        - "**/index.md"
        - "**/api.md.tmpl"
      - source: docs/spec/index.md
        target: content/registry/spec/_index.md
      - source: docs/spec/auth/index.md
        target: content/registry/spec/auth/_index.md


outputFormats:
  redirects:
    baseName: redirects
    isPlainText: true
    mediaType: "application/json"
    notAlternative: true
  robots:
    baseName: robots
    isPlainText: true
    mediaType: "text/plain"
    notAlternative: true

outputs:
  home:
    - html
    - redirects
    - robots
  term:
    - html
    - json

taxonomies:

languages:
  en:
    languageName: English
