algolia_appid: 3XRLW0LZH9
algolia_apikey: 2899036ce47dba191b8dc1758e4bc6a4
versions:
  latest_engine_api_version: "1.41"
  docker_ce_version: "20.10"
  compose_v1_version: "1.29.2"
  compose_version: "v2.13.0"
  compose_file_v3: "3.9"
  compose_file_v2: "2.4"
  machine_version: "0.16.0"
  distribution_version: "2.7"
  compose_switch_version: "1.0.4"
  buildkit_version: "0.10.5"
  min_api_threshold: 1.40
